fail_fast: true
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        files: \.(yaml|yml)$
      - id: end-of-file-fixer
        files: \.py$
      - id: trailing-whitespace
        files: \.py$
      - id: check-ast
        files: \.py$
      - id: mixed-line-ending
      - id: detect-private-key

  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        name: "Formatting"
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        files: \.py$
        language_version: python3.12